# HW

In [1]:
import numpy as np
import pandas as pd

##### Загрузите датасет titanic.csv

In [2]:
df_titanic = pd.read_csv('titanic.csv')

In [3]:
df_titanic.head(30)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   
20                               Fynney, Mr. Joseph J    male  35.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   
22                        McGowan, Miss. Anna "Annie"  female  15.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   
24                      Palsson, Miss. Torborg Danira  female   8.0      3   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
26                            Emir, Mr. Farred Chehab    male   NaN      0   
27                     Fortune, Mr. Charles Alexander    male  19.0      3   
28                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0   
29                                Todoroff, Mr. Lalio    male   NaN      0   

    Parch            Ticket      Fare        Cabin Embarked  
0       0         A/5 21171    7.2500          NaN        S  
1       0          PC 17599   71.2833          C85        C  
2       0  STON/O2. 3101282    7.9250          NaN        S  
3       0            113803   53.1000         C123        S  
4       0            373450    8.0500          NaN        S  
5       0            330877    8.4583          NaN        Q  
6  

In [4]:
df_titanic.shape

(891, 12)

In [5]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


> Обратите внимание на разное количество значений переменных
Если это так - то у вас пропуски в данных. Такое бывает. 
Например в этом датасете не получилось выяснить всех подробностей у некоторых людей в виду утери данных, невозможности узнать или восстановить их

In [6]:
df_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

> Давайте возьмем для начала только несколько признаков, позже - вы увеличите их количество и сделаете соответствующую обработку.

In [7]:
columns = ['Sex', 'Age', 'Pclass', 'Survived']

In [8]:
simple_train = df_titanic[columns].loc[:500]
simple_test = df_titanic[columns].loc[500:]

> мы пока не умеем на уровне алгоритма работать с пропущенными значениями. 
Представьте вам дают 5-мерный вектор у которого заполнены только три компоненты и другой такой же вектор но у него заполнены лишь две  компоненты.  Как померить их сходство????

distance_between( [1,0,1, NaN, NaN], [NaN, 1, 1, NaN, NaN] )


> один из вариантов - заполнить какими то значениями - например если это возраст - то заполнить средним по датасету или нулем.

>> на будущее - в sklearn есть такой модуль - http://scikit-learn.org/stable/modules/impute.html но сейчас можете заполнить пропуски средствами pandas - метод fillna()

##### Заполните пропущенные значения чем нибудь

In [9]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [10]:
df_titanic = df_titanic.fillna({'Age' : df_titanic['Age'].mean()})
simple_train = df_titanic[columns].loc[:500]
simple_test = df_titanic[columns].loc[500:]
df_titanic

# можно inplace делать такое, а можно переприсваивать.

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
5                                     Moran, Mr. James    male  29.699118   
6                              McCarthy, Mr. Timothy J    male  54.000000   
7                       Palsson, Master. Gosta Leonard    male   2.000000   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000   
10                     Sandstrom, Miss. Marguerite Rut  female   4.000000   
11                            Bonnell, Miss. Elizabeth  female  58.000000   
12                      Saundercock, Mr. William Henry    male  20.000000   
13                         Andersson, Mr. Anders Johan    male  39.000000   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.000000   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.000000   
16                                Rice, Master. Eugene    male   2.000000   
17                        Williams, Mr. Charles Eugene    male  29.699118   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.000000   
19                             Masselmani, Mrs. Fatima  female  29.699118   
20                             

> мы чемпионы. Но мы понимаем, что алгоритм у нас метрический - он не понимает как померить близость векторов в которых содержатся строки

distance( [1,1,0,'мужик'], [1, 0, 1, 'принцесска'] )

> поэтому давайте заведем признак is_man который будет принимать значение 0 или 1.

##### Заведите бинарный признак отвечающий за пол. Строковый удалите

хинт - есть метод apply()

In [11]:
def sex_to_binary(item):
    if item == 'male':
        return 1
    elif item == 'female':
        return 0
    else:
        pass

In [12]:
simple_train.Sex = simple_train.Sex.apply(sex_to_binary)
simple_test.Sex = simple_test.Sex.apply(sex_to_binary)

In [13]:
simple_test

Sex        Age  Pclass  Survived
500    1  17.000000       3         0
501    0  21.000000       3         0
502    0  29.699118       3         0
503    0  37.000000       3         0
504    0  16.000000       1         1
505    1  18.000000       1         0
506    0  33.000000       2         1
507    1  29.699118       1         1
508    1  28.000000       3         0
509    1  26.000000       3         1
510    1  29.000000       3         1
511    1  29.699118       3         0
512    1  36.000000       1         1
513    0  54.000000       1         1
514    1  24.000000       3         0
515    1  47.000000       1         0
516    0  34.000000       2         1
517    1  29.699118       3         0
518    0  36.000000       2         1
519    1  32.000000       3         0
520    0  30.000000       1         1
521    1  22.000000       3         0
522    1  29.699118       3         0
523    0  44.000000       1         1
524    1  29.699118       3         0
525    1  40.500000       3         0
526    0  50.000000       2         1
527    1  29.699118       1         0
528    1  39.000000       3         0
529    1  23.000000       2         0
..   ...        ...     ...       ...
861    1  21.000000       2         0
862    0  48.000000       1         1
863    0  29.699118       3         0
864    1  24.000000       2         0
865    0  42.000000       2         1
866    0  27.000000       2         1
867    1  31.000000       1         0
868    1  29.699118       3         0
869    1   4.000000       3         1
870    1  26.000000       3         0
871    0  47.000000       1         1
872    1  33.000000       1         0
873    1  47.000000       3         0
874    0  28.000000       2         1
875    0  15.000000       3         1
876    1  20.000000       3         0
877    1  19.000000       3         0
878    1  29.699118       3         0
879    0  56.000000       1         1
880    0  25.000000       2         1
881    1  33.000000       3         0
882    0  22.000000       3         0
883    1  28.000000       2         0
884    1  25.000000       3         0
885    0  39.000000       3         0
886    1  27.000000       2         0
887    0  19.000000       1         1
888    0  29.699118       3         0
889    1  26.000000       1         1
890    1  32.000000       3         0

[391 rows x 4 columns]

In [14]:
max_ = simple_train.max(axis=0)
min_ = simple_train.min(axis=0)
simple_train = (simple_train - min_) / (max_ - min_)

max_ = simple_test.max(axis=0)
min_ = simple_test.min(axis=0)
simple_test = (simple_test - min_) / (max_ - min_)

##### Сформируйте трейн и тест выборку, где в X лежат признаки 'Sex', 'Age', 'Pclass', а в у - Survived

Результат - numpy array

hint - у pandas есть метод drop() и атрибут values; Пощупайте их

In [15]:
X_train = simple_train.drop(columns='Survived').values
X_test = simple_test.drop(columns='Survived').values
y_train = simple_train['Survived'].values
y_test = simple_test['Survived'].values
X_test


array([[1.        , 0.2083438 , 1.        ],
       [0.        , 0.25860769, 1.        ],
       [0.        , 0.36792055, 1.        ],
       ...,
       [0.        , 0.36792055, 1.        ],
       [1.        , 0.32143755, 0.        ],
       [1.        , 0.39683338, 1.        ]])

In [16]:
assert isinstance(X_train, np.ndarray)
assert isinstance(X_test, np.ndarray)
assert isinstance(y_train, np.ndarray)
assert isinstance(y_test, np.ndarray)

In [17]:
assert X_train.shape[0] == y_train.shape[0]
assert X_test.shape[0] == y_test.shape[0]

In [18]:
assert not np.any(np.isnan(X_train)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'
assert not np.any(np.isnan(X_test)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'

##### Реализуйте KNN. Сами, как делали это на лекции. 

Можете улучшить его.
(например использовать kd-tree для быстрого поиска ближайших соседей, 
 или обходить соседей и класть расстояния в мин-кучу - тогда вы быстрее будете набирать их, без сортировки.)

In [19]:
class KNN:
    """
    simple KNN classifier with O(n) complexity for memory,
    and O(n log n) complexity - for nn search.
    """
    
    def __init__(self, n):
        self.n = n
        
    def fit(self, X, y):
        self.X = X
        self.y = y
    
    def predict(self, X):
        y_hat = []
        assert len(X.shape) == 2
        for str_ in X:
            
            dist = 0.
            for i, val in enumerate(str_):
                dist += (self.X[:, i] - val)**2
            dist = np.sqrt(dist)
            
            idx = np.argsort(dist)[:self.n]
            counts = np.bincount(self.y[idx].astype(int))
            prediction = np.argmax(counts)
            y_hat.append(prediction)
            
        return np.array(y_hat)

In [20]:
knn = KNN(5)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
y_pred

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,

##### посчитайте руками (не используя sklearn) качество вашего предсказания

In [21]:
acc = np.mean(y_pred == y_test)
print('доля правильных ответов:', acc)

доля правильных ответов: 0.7979539641943734


In [22]:
np.unique(y_pred)

array([0, 1])

> Мы получили бейслайн решение. Оно должно давать скорр в районе 0.76

____

In [23]:
### можете проверить себя

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7979539641943734


In [24]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

np.unique(y_pred)

print(accuracy_score(y_test, y_pred))

0.80306905370844


##### TODO продолжение домашки

In [25]:
df_titanic = pd.read_csv('titanic.csv')

In [26]:
columns = ['Sex', 'Age', 'Pclass', 'Survived', 'Fare', 'Embarked', 'Cabin']
df_titanic = df_titanic[columns]

In [27]:
def sex_to_binary(item):
    if item == 'male':
        return 1
    elif item == 'female':
        return 0
    else:
        pass

In [28]:
df_titanic['Sex'] = df_titanic['Sex'].apply(sex_to_binary)
df_titanic = df_titanic.fillna({'Age' : df_titanic['Age'].mean(), 'Embarked' : df_titanic['Embarked'].mode()[0]})
df_titanic['Cabin'] = df_titanic['Cabin'].apply(lambda x: x[0] if type(x)==str else np.nan)

for pas_class in range(1,4):
    df_titanic[df_titanic['Pclass'] == pas_class] = df_titanic[df_titanic['Pclass'] == pas_class].fillna(value = df_titanic[df_titanic['Pclass'] == pas_class]['Cabin'].mode()[0])



In [29]:
df_titanic['Cabin'] = df_titanic['Cabin'].map(df_titanic.groupby('Cabin').size())
df_titanic['Embarked'] = df_titanic['Embarked'].map(df_titanic.groupby('Embarked').size())

In [30]:
df_titanic

Sex        Age  Pclass  Survived      Fare  Embarked  Cabin
0      1  22.000000       3         0    7.2500       646    660
1      0  38.000000       1         1   71.2833       168     99
2      0  26.000000       3         1    7.9250       646    660
3      0  35.000000       1         1   53.1000       646     99
4      1  35.000000       3         0    8.0500       646    660
5      1  29.699118       3         0    8.4583        77    660
6      1  54.000000       1         0   51.8625       646     32
7      1   2.000000       3         0   21.0750       646    660
8      0  27.000000       3         1   11.1333       646    660
9      0  14.000000       2         1   30.0708       168    660
10     0   4.000000       3         1   16.7000       646      4
11     0  58.000000       1         1   26.5500       646     99
12     1  20.000000       3         0    8.0500       646    660
13     1  39.000000       3         0   31.2750       646    660
14     0  14.000000       3         0    7.8542       646    660
15     0  55.000000       2         1   16.0000       646    660
16     1   2.000000       3         0   29.1250        77    660
17     1  29.699118       2         1   13.0000       646    660
18     0  31.000000       3         0   18.0000       646    660
19     0  29.699118       3         1    7.2250       168    660
20     1  35.000000       2         0   26.0000       646    660
21     1  34.000000       2         1   13.0000       646     33
22     0  15.000000       3         1    8.0292        77    660
23     1  28.000000       1         1   35.5000       646     15
24     0   8.000000       3         0   21.0750       646    660
25     0  38.000000       3         1   31.3875       646    660
26     1  29.699118       3         0    7.2250       168    660
27     1  19.000000       1         0  263.0000       646     99
28     0  29.699118       3         1    7.8792        77    660
29     1  29.699118       3         0    7.8958       646    660
..   ...        ...     ...       ...       ...       ...    ...
861    1  21.000000       2         0   11.5000       646    660
862    0  48.000000       1         1   25.9292       646     33
863    0  29.699118       3         0   69.5500       646    660
864    1  24.000000       2         0   13.0000       646    660
865    0  42.000000       2         1   13.0000       646    660
866    0  27.000000       2         1   13.8583       168    660
867    1  31.000000       1         0   50.4958       646     15
868    1  29.699118       3         0    9.5000       646    660
869    1   4.000000       3         1   11.1333       646    660
870    1  26.000000       3         0    7.8958       646    660
871    0  47.000000       1         1   52.5542       646     33
872    1  33.000000       1         0    5.0000       646     47
873    1  47.000000       3         0    9.0000       646    660
874    0  28.000000       2         1   24.0000       168    660
875    0  15.000000       3         1    7.2250       168    660
876    1  20.000000       3         0    9.8458       646    660
877    1  19.000000       3         0    7.8958       646    660
878    1  29.699118       3         0    7.8958       646    660
879    0  56.000000       1         1   83.1583       168     99
880    0  25.000000       2         1   26.0000       646    660
881    1  33.000000       3         0    7.8958       646    660
882    0  22.000000       3         0   10.5167       646    660
883    1  28.000000       2         0   10.5000       646    660
884    1  25.000000       3         0    7.0500       646    660
885    0  39.000000       3         0   29.1250        77    660
886    1  27.000000       2         0   13.0000       646    660
887    0  19.000000       1         1   30.0000       646     47
888    0  29.699118       3         0   23.4500       646    660
889    1  26.000000       1         1   30.0000       168     99
890    1  32.000000       3         0   

In [31]:
simple_train = df_titanic[columns].loc[:500]
simple_test = df_titanic[columns].loc[500:700]
simple_val = df_titanic[columns].loc[700:]

In [32]:
max_train = simple_train.max(axis = 0)
min_train = simple_train.min(axis = 0)

simple_train = (simple_train - min_train) / (max_train - min_train)

max_test = simple_test.max(axis = 0)
min_test = simple_test.min(axis = 0)

simple_test = (simple_test - min_test) / (max_test - min_test)

max_val = simple_val.max(axis = 0)
min_val = simple_val.min(axis = 0)

simple_val = (simple_val - min_val) / (max_val - min_val)

In [33]:
X_train = simple_train.drop('Survived', axis=1).values
X_test = simple_test.drop('Survived', axis=1).values
X_val = simple_val.drop('Survived', axis=1).values
y_train = simple_train['Survived'].values
y_test = simple_test['Survived'].values
y_val = simple_val['Survived'].values

In [34]:
print(X_test)
print(X_train)
print(X_val)
print(y_test)
print(y_train)
print(y_val)


[[1.         0.20504732 1.         0.01690807 1.         1.        ]
 [0.         0.2555205  1.         0.01512699 0.         1.        ]
 [0.         0.36528855 1.         0.01489121 0.         1.        ]
 ...
 [1.         0.60883281 0.         0.21642979 0.1599297  0.13023256]
 [1.         0.52050473 1.         0.01493181 1.         1.        ]
 [0.         0.21766562 0.         0.44409922 0.1599297  0.13023256]]
[[1.         0.3024911  1.         0.01415106 1.         1.        ]
 [0.         0.53024911 0.         0.13913574 0.1599297  0.14871017]
 [0.         0.3594306  1.         0.01546857 1.         1.        ]
 ...
 [0.         0.34519573 0.         0.2958059  1.         0.14871017]
 [1.         0.33096085 1.         0.01521639 1.         1.        ]
 [1.         0.23131673 1.         0.01690807 1.         1.        ]]
[[0.         0.23892362 0.         0.44409922 0.1599297  0.13023256]
 [1.         0.46996466 0.         0.05130978 1.         0.02635659]
 [0.         0.2389236

In [35]:
best = (0, 0.0)
for par in range(1, 25):
    knn = KNN(par)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_val)
    acc = np.mean(y_pred == y_val)
    print('knn parameter = {} : % = {}'.format(par, acc))
    if acc > best[1]:
        best = (par, acc)

print('best parameter is {}'.format(best[0]))

knn parameter = 1 : % = 0.7643979057591623
knn parameter = 2 : % = 0.806282722513089
knn parameter = 3 : % = 0.7905759162303665
knn parameter = 4 : % = 0.8115183246073299
knn parameter = 5 : % = 0.8272251308900523
knn parameter = 6 : % = 0.8219895287958116
knn parameter = 7 : % = 0.8324607329842932
knn parameter = 8 : % = 0.8219895287958116
knn parameter = 9 : % = 0.8272251308900523
knn parameter = 10 : % = 0.8324607329842932
knn parameter = 11 : % = 0.8324607329842932
knn parameter = 12 : % = 0.8167539267015707
knn parameter = 13 : % = 0.8115183246073299
knn parameter = 14 : % = 0.8167539267015707
knn parameter = 15 : % = 0.8167539267015707
knn parameter = 16 : % = 0.8219895287958116
knn parameter = 17 : % = 0.8219895287958116
knn parameter = 18 : % = 0.8219895287958116
knn parameter = 19 : % = 0.8115183246073299
knn parameter = 20 : % = 0.8219895287958116
knn parameter = 21 : % = 0.8219895287958116
knn parameter = 22 : % = 0.8219895287958116
knn parameter = 23 : % = 0.821989528795811

In [36]:
knn = KNN(best[0])
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print('процент правильных ответов = {}'.format(np.mean(y_pred == y_test)))

процент правильных ответов = 0.7661691542288557
